apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-order-service
  labels:
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
      - name: item-order-service
        image: eu.gcr.io/item-order/item-order-service:1.3