apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-order-system
  labels:
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
      - name: item-order-system
        image: eu.gcr.io/item-order/item-order-system:1.3.0